pipeline{
    agent any
    
    stages {
        
        stage('Build Application') 
         {
            
            steps
            {
                
                bat 'mvn -f integ-Maven-tutorial/pom.xml clean package'
                
            }
            post{
                success {
                    
                    echo "Archiving the artifacts ......."
                    
                    archiveArtifacts artifacts: '**/*.war'
                }

                
                
            }

            
            
        }
        stage('Deploy in staging environment') 
        {
            
            build job: 'Deploy_application_staging_env'
            
        }
        stage('Deploy in production environment') 
        {
              steps{
                timeout(time:5, unit:'DAYS'){
                 input message:'Approve PRODUCTION Deployment?'
                } 
            
            build job: 'Deploy_application_production_env'
            
        }

        }
        
    }

}

   

    
    
    
    

