pipeline{
    agent any
    
    stages {
        
        stage {
            
            steps('Build Application') {
                
                sh 'mvn clean package'
                
            }
            post{
                success {
                    
                    echo "Archiving the artifacts ......."
                    
                    archiveArtifacts artifacts: '**/*.war'
                }

                
                
            }

            
            
        }

        
        
    }

}

   

    
    
    
    

